name: Image Minimizer

permissions:
  issues: write
  pull-requests: write

on:
  issue_comment:
    types: [created, edited]
  issues:
    types: [opened, edited]
  pull_request:
    types: [opened, edited]

jobs:
  try-minimize:
    runs-on: ubuntu-latest

    steps:
      - name: Minimize simple images
        uses: actions/github-script@v5
        with:
          script: |
            var initialBody = null;
            if (context.eventName == "issue_comment") {
              initialBody = context.comment.body
            } else if (context.eventName == "issue") {
              initialBody = context.issue.body
            } else if (context.eventName == "pull_request") {
              initialBody = context.pull_request.body
            } else {
              console.log("Aborting: No body found")
              return
            }
            console.log("Found body", initialBody);
            
            // Regex for finding images (simple variant)
            const REGEX_IMAGE_LOOKUP = /\!\[(.{1,})\]\((https:\/\/[-a-z0-9]{1,}\.githubusercontent\.com\/\d+\/[-0-9a-f]{32,}\.(jpg|gif|png))\)/gm
            
            var foundSimpleImages = REGEX_IMAGE_LOOKUP.test(initialBody);
            if (!foundSimpleImages) {
              console.log('Found no simple images to process');
              return;
            }
            
            var newBody = initialBody + " bot was here"
            
            if (context.eventName == "issue_comment") {
              console.log("Updating comment with id", context.comment.id)
              await github.rest.issues.updateComment({
                comment_id: context.comment.id,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: newBody
              })
            } else if (context.eventName == "issue") {
              console.log("Updating issue", context.issue.number)
              await github.rest.issues.update({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: newBody
              });
            } else if (context.eventName == "pull_request") {
              console.log("Updating PR", context.pull_number.number)
              await github.rest.pulls.update({
                pull_number: context.pull_number.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: newBody
              });
            }
